# NumPy Arrays

In [5]:
my_list = [1,2,3 ]

In [6]:
import numpy as np

In [7]:
np.array(my_list)

array([1, 2, 3])

#### Creating a numpy array from a python list

In [8]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### we know this is an 2d array because of the way its presented as an output but also
#####  because it has 2 sets of square brackets

### most common way of creating a numpy array is using np.arange()

#### it works like pythons own range function, pass in start argument 1 and and stop argument 2 

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### a third argument dictates step size

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

##### np.zeros(3) gives out a 1d vector

##### or pass a tuple: passing in num of rows, num of colums

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

zeros((5,5)) = num of rows, num of colums

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

#### returns a 1-d vector - as noted by the one set of brackets

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

#### linspace takes third argument of how many points you want, it gives a 1D array as seen by the brackets
#### arange takes third argument of what stepsize you want to step through 

### The Identity Matrix is useful in algebra and when performing equasions

- it only takes one parameter, because it is always a square and 1's go diagonally down the square

- number of rows always equals nuymber of columns 

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Numpy also has lots of ways of creating random arrays

- np.random. then **clicking tab** will show you all the methods associated with random

In [20]:
np.random.rand(5)

array([0.02373044, 0.8242952 , 0.6233007 , 0.00092269, 0.60316835])

#### rand - creates an array of the specified size of uniform distribution from 0 - 1

In [21]:
np.random.rand(5,5)

array([[0.46140892, 0.79239536, 0.36309963, 0.93821601, 0.3425587 ],
       [0.26697788, 0.48341066, 0.88171403, 0.28018179, 0.29468126],
       [0.80434328, 0.47370804, 0.30983073, 0.88817166, 0.04303002],
       [0.6588423 , 0.76730789, 0.13354985, 0.52104278, 0.9799925 ],
       [0.52684405, 0.48261141, 0.48506029, 0.05447664, 0.155843  ]])

#### randn returns numbers not from a uniform distribution but from a standard normal distribution or gausian distribution,centered around 0

In [26]:
np.random.rand(2)

array([0.2356419 , 0.02547833])

#### If i pass each dimention as a seperate argument, I get a 2-d array, seen by the 2 sets of brackets

In [28]:
np.random.randn(4,4)

array([[ 0.41799373,  1.38993556,  0.36825053,  1.96779083],
       [ 0.07893132, -2.18615245, -1.78970929, -1.18516881],
       [-1.19966589,  0.39726159,  0.87565149,  0.33712069],
       [-1.08905202, -0.11294573, -0.9025448 ,  0.1301898 ]])

#### rand int returns random integers from a low to a high number

In [30]:
np.random.randint(1,100)

32

#### lowest incusive highest exclusive. i.e 1 can be selected as the random integer from 1-100 but 100 does not.

In [31]:
np.random.randint(1,100,10)

array([64, 58, 39, 19, 24, 98, 32, 99,  8, 73])

#### 10 random numbers from 1-99

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10) 

In [28]:
ranarr

array([34, 35,  0,  7,  0,  6,  4, 46, 34,  6])

#### reshape returns an array of the same data but with a new shape

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.reshape(5,2)

ValueError: cannot reshape array of size 25 into shape (5,2)

#### this wont work because you must match the size of the array elements you had, to the new array shape you wish to have

### a good way to check this is the number of rows x columns is equal to the number of elements, i.e. 5x5 = 25

In [32]:
ranarr.max()

46

In [33]:
ranarr.min()

0

In [34]:
ranarr

array([34, 35,  0,  7,  0,  6,  4, 46, 34,  6])

#### if i want to know at exactly what index value the number is at, i can do is argmax i.e. it tells me the max number in my array is 46 and its at the position 2 in the array

In [35]:
ranarr.argmax() 

7

In [36]:
ranarr.argmin()

2

In [37]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

#### after I reshape the array, i see its now a 5x5 2-d array

In [44]:
arr.dtype

dtype('int32')

##### dtype returns the type of the thing

#### to make a shortcut instead of writing np.random.you can do

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

7

# Numpy Indexing and Selection

In [47]:
import numpy as np

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[8]

8

In [52]:
arr[1:5]

array([1, 2, 3, 4])

##### 1:5 slices the array

In [54]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

#### :6 everything up to 6, same as 0:6

In [55]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### numPy arrays can broadcast

In [57]:
arr[0:5] = 100

In [58]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
slice_of_arr = arr[0:6]

In [62]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [66]:
slice_of_arr[:] = 99

### The above says
- take a slice of the array, the slice being the whole arrray
- change the values to 99

In [68]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### this actually changes the original array, it does not make a copy of it

- so therefore we make a copy

In [71]:
arr_copy = arr.copy()

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy[:] = 100

In [75]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

### here we have broadcast all the items in the COPY array to 100

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## accessing elements in a 2d array

In [78]:
arr_2d = np.array([[5,10,15],[20,25,30],[35, 40, 45]])

In [79]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [80]:
arr_2d[2][1]

40

In [81]:
arr_2d[2,1]

40

#### doing arr_2d[2][1] and arr_2d[2,1] is the same but arr_2d[2,1] is reccomended

### to grab sections of the array

In [84]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [86]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

### arr_2d[:2] says grab everything to row 2: Row 0 and Row 1 are returned

In [88]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [89]:
arr_2d[:1]

array([[ 5, 10, 15]])

In [90]:
arr_2d[1:2]

array([[20, 25, 30]])

In [91]:
arr_2d[2:3]

array([[35, 40, 45]])

In [92]:
arr_2d[:3,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [93]:
arr_2d[2:3]

array([[35, 40, 45]])

In [94]:
arr_2d[2:3, :2]

array([[35, 40]])

In [96]:
arr_2d[2:3, 2:3]

array([[45]])

In [97]:
arr = np.arange(1,11)

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
bool_arr = arr > 5

In [102]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [104]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

### Taking an array and doing a comparison operation on it:
- returns an array of booleans: A Boolean Array
- can use the boolean array to conditionally select elements from the original array
- where it was true

In [106]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

### the above SYNTAX IS USED ALL THE TIME FOR CONDITIONAL SELECTION

##### If we want to know all the elements of the array that are less than three we would do:

In [109]:
arr[arr<3]

array([1, 2])